version: '3'
services:
  proxy:
    image: nginx:1.19.1
    container_name: ${APP_NAME}-proxy
    ports:
      - 8085:8085
    depends_on:
      - php
      - db
    volumes:
      - ./proxy/server.conf:/etc/nginx/conf.d/default.conf
      - ../php/:/var/www/html
    environment:
      - APP_NAME=$APP_NAME
  php:
    build: ./php
    container_name: ${APP_NAME}-php
    depends_on:
      - db
    volumes:
      - ../php/:/var/www/html
      - ./php/log/:/var/log/php/
    tty: true
    environment:
      - APP_NAME=$APP_NAME
      - DB_DATABASE=$DB_DATABASE
      - DB_PASSWORD=$DB_PASSWORD
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=$DB_PASSWORD
    depends_on:
      - db
    ports:
      - 8086:80
  db:
    # platform: 'linux/amd64'
    container_name: ${APP_NAME}-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/log:/var/log/mysql
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 23306:3306
    tty: true
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
